name: Your New Jekyll Site
markdown: redcarpet
pygments: true
host: 127.0.0.1
port: 8888
exclude: ['bower_components', 'Gemfile', 'Gemfile.lock', 'bower.json', '.gitignore', 'Gruntfile.js', 'package.json']
